### ISSUE TITLE
Deprecate UndefinedBox and RelativeBox

### ISSUE THREAD

**Issue by ausi** [contao/imagine-svg#12]
I think we should deprecate the following interfaces and classes:

- `UndefinedBoxInterface`
- `RelativeBoxInterface`
- `UndefinedBox`
- `RelativeBox`

And instead add an `SvgBox` with the methods `isUndefined` and `isRelative`. An interface for this class is not needed IMO.

Also `getWidth()` and `getHeight()` should probably throw an exception for an  undefined box instead of returning zero.

**Comment by ausi** [comment]
Or instead of `isUndefined()` and `isRelative()` a `getSvgType()` method that returns `TYPE_EXACT`, `TYPE_RELATIVE` or `TYPE_UNDEFINED`.

_I should probably look up how these terms are called in the SVG spec._

**Comment by ausi** [comment]
> Also `getWidth()` and `getHeight()` should probably throw an exception for an undefined box instead of returning zero.

Probably better to return the [default object size](https://html.spec.whatwg.org/multipage/media.html#the-video-element:default-object-size) of `300` by `150`

> _I should probably look up how these terms are called in the SVG spec._

From the SVG spec I think the naming should be `TYPE_ABSOLUTE`, `TYPE_ASPECT_RATIO` and `TYPE_NONE`.

**Comment by leofeyer** [comment]
+1 for default object size instead of exception.

**Comment by ausi** [comment]
Closed in favor of #14
