### ISSUE TITLE
New major version 1.0.0

### ISSUE THREAD

**Issue by ausi** [contao/imagine-svg#22]
We just released a release candidate version for the new major: <https://github.com/contao/imagine-svg/releases/tag/1.0.0-RC1>

It would probably make sense to test the new `"contao/imagine-svg": "1.0.0@RC"` version in the dependent packages to verify that we didn’t break their usage of the library:

- [x] `contao/image` https://github.com/contao/image/pull/71
- [x] `contao/contao` https://github.com/contao/contao/pull/1827
- [x] `sulu/sulu` @alexander-schranz ?
- [ ] ~~`bolt/thumbs` and `bolt/filesystem` @CarsonF ?~~
- [ ] ~~rokka.io @chregu if you still use this library there?~~

**Comment by alexander-schranz** [comment]
@ausi Can confirm that the 1.0.0@RC works on @sulu side. Thank you for your work :+1:

**Comment by ausi** [comment]
Released: https://github.com/contao/imagine-svg/releases/tag/1.0.0

**Comment by alexander-schranz** [comment]
@ausi thats great News. Thank you!
