### ISSUE TITLE
No Documentation to use Colorize method? 

### ISSUE THREAD

**Issue by rashidaghadiinfotech** [contao/imagine-svg#36]
How can I change the color of Black SVG to any RGB color? 
I am using this library for modifying size and getting the size. What is the way to change fill color of SVG? 

`$imagine = new Imagine();
  $image = $imagine->open($svg_file);
  $image->resize(new Box(300, 300));
  
//  $image->effects()->colorize($image->palette(), array(255,0,0));
   
  $image->save($file_path);`

So what is the solution to change it to color we want? I have no idea about using colorize method properly.

**Comment by ausi** [comment]
You can find the documentation here: https://imagine.readthedocs.io/en/stable/usage/effects.html

```php
$image->effects()->colorize($image->palette()->color('#FF0000'));
```

**Comment by rashidaghadiinfotech** [comment]
@ausi 
Thank you for this help. It worked magically.
